/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica.Operacoes;

import javax.swing.JOptionPane;
import RMI.Cliente;
import RMI.InterfaceServ;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Felipe Lopes Zem
 */
public class IG_Op_VendasHospedagem extends javax.swing.JFrame {
    private static final byte 
            DADOS_NENHUM = 0, 
            DADOS_INSERIR = 1, 
            DADOS_MODIFICAR = 2,
            DADOS_EXCLUIR = 3;
    
    /**
     * Use esta variável para identificar qual o modo de manipulação de dados está 
     * sendo utilizado no presente momento por este componente da Interface Gráfica.
     * 
     * As constantes aceitas são: DADOS_NENHUM (nenhum, apenas consulta), DADOS_INSERIR, 
     * DADOS_MODIFICAR, DADOS_EXCLUIR.
     */
    private byte modoDeDados = 0;
    
    /**
     * Creates new form IG_CadastroSimples_teste
     */
    public IG_Op_VendasHospedagem() {
        initComponents();
        b_AtualizarActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_elementos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_idPacoteTuristico = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_cliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_cartao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_parcelas = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_numeroPessoas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_valorTotal = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_itensDosElementos = new javax.swing.JTable();
        b_EditarItensDaVenda = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        b_Inserir = new javax.swing.JButton();
        b_Modificar = new javax.swing.JButton();
        b_Excluir = new javax.swing.JButton();
        b_Atualizar = new javax.swing.JButton();
        b_Cancelar = new javax.swing.JButton();
        b_Ok = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Todas as vendas de hospedagem"));

        table_elementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_elementos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jScrollPane3.setBorder(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do cadastro"));

        jLabel1.setText("ID");

        jLabel7.setText("ID do pacote turístico");

        tf_idPacoteTuristico.setEnabled(false);

        jLabel2.setText("Cliente");

        tf_cliente.setEnabled(false);

        jLabel5.setText("Cartão");

        tf_cartao.setEnabled(false);

        jLabel6.setText("Parcelas");

        tf_parcelas.setEnabled(false);

        jLabel3.setText("Número de pessoas");

        tf_numeroPessoas.setEnabled(false);

        jLabel4.setText("Valor total");

        tf_valorTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_idPacoteTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_cartao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_numeroPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_idPacoteTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_cartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_parcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_numeroPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_valorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane3.setViewportView(jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ítens da venda"));

        table_itensDosElementos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table_itensDosElementos);

        b_EditarItensDaVenda.setText("Editar itens da venda");
        b_EditarItensDaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_EditarItensDaVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_EditarItensDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(b_EditarItensDaVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        b_Inserir.setText("Inserir");
        b_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_InserirActionPerformed(evt);
            }
        });

        b_Modificar.setText("Modificar");
        b_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ModificarActionPerformed(evt);
            }
        });

        b_Excluir.setText("Excluir");
        b_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ExcluirActionPerformed(evt);
            }
        });

        b_Atualizar.setText("Atualizar");
        b_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AtualizarActionPerformed(evt);
            }
        });

        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        b_Ok.setText("Ok");
        b_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(b_Inserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(b_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Ok))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_Atualizar, b_Cancelar, b_Excluir, b_Inserir, b_Modificar, b_Ok});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(b_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(b_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b_Atualizar, b_Cancelar, b_Excluir, b_Inserir, b_Modificar, b_Ok});

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ESTE MÉTODO SÓ DEVE SER UTILIZADO PARA TESTAR INDIVIDUALMENTE ESTE MÓDULO!
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new IG_Op_VendasHospedagem().setVisible(true);
        });
    }
    
    /**
     * Ao clicar no botão Inserir é ativado o modo de Inserção de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que um
     * novo item seja cadastrado.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a inclusão. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_InserirActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(false);
        b_Modificar.setEnabled(false);
        b_Excluir.setEnabled(false);
        b_Atualizar.setEnabled(false);
        //Bloqueia a ativação dos demais recursos
        b_EditarItensDaVenda.setEnabled(false);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da inclusão.
        b_Cancelar.setEnabled(true);
        b_Ok.setEnabled(true);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(true);   //O BD GERA ID SEQUENCIAL!
        tf_idPacoteTuristico.setEnabled(true);
        tf_cliente.setEnabled(true);
        tf_cartao.setEnabled(true);
        tf_parcelas.setEnabled(true);
        tf_numeroPessoas.setEnabled(true);
        //tf_valorTotal.setEnabled(true);     //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Limpa os campos de edição dos componentes, para que novos valores sejam informados.
        tf_id.setText("");
        tf_idPacoteTuristico.setText("");
        tf_cliente.setText("");
        tf_cartao.setText("");
        tf_parcelas.setText("");
        tf_numeroPessoas.setText("");
        tf_valorTotal.setText("");
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_INSERIR;
    }//GEN-LAST:event_b_InserirActionPerformed

    /**
     * Ao clicar no botão Modificar é ativado o modo de Modificação de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que o
     * ítem que estiver selecionado no painel "Todos os itens" possa ser modificado.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a modificação. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ModificarActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(false);
        b_Modificar.setEnabled(false);
        b_Excluir.setEnabled(false);
        b_Atualizar.setEnabled(false);
        //Bloqueia a ativação dos demais recursos
        b_EditarItensDaVenda.setEnabled(false);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
        b_Cancelar.setEnabled(true);
        b_Ok.setEnabled(true);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(true);   //O BD GERA ID SEQUENCIAL!
        tf_idPacoteTuristico.setEnabled(true);
        tf_cliente.setEnabled(true);
        tf_cartao.setEnabled(true);
        tf_parcelas.setEnabled(true);
        tf_numeroPessoas.setEnabled(true);
        //tf_valorTotal.setEnabled(true);     //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_MODIFICAR;
    }//GEN-LAST:event_b_ModificarActionPerformed

    /**
     * Ao clicar no botão Excluir é ativado o modo de Exclusão de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que o
     * ítem que estiver selecionado no painel "Todos os itens" possa ser excluído.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a exclusão. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ExcluirActionPerformed
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_EXCLUIR;
        //TODO usar JOPtionPane para confirmar a exclusão
    }//GEN-LAST:event_b_ExcluirActionPerformed

    /**
     * Ao clicar no botão Atualizar todos os dados de itens já cadastrados no painel
     * "Todos os itens" são atualizados.
     * @param evt 
     */
    private void b_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AtualizarActionPerformed
        try {
            InterfaceServ servente;
            servente = Cliente.getServer();
            table_elementos.setModel(
                    servente.consultarDB("select * from vendasdehospedagem")
            );
        } catch (RemoteException ex) {
            Logger.getLogger(IG_Op_VendasHospedagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_AtualizarActionPerformed

    /**
     * Ao clicar no botão Cancelar o modo de manipulação de dados atual é abortado,
     * retornando para o estado DADOS_NENHUM, reabilitando os botões Inserir, Modificar,
     * Excluir e Atualizar e bloqueando os botões Cancelar e Ok.
     * 
     * Os componentes do painel "Dados do cadastro" ficam novamente bloqueados, para
     * que seja permitido apenas a consulta dos mesmos.
     * @param evt 
     */
    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(true);
        b_Modificar.setEnabled(true);
        b_Excluir.setEnabled(true);
        b_Atualizar.setEnabled(true);
        //Bloqueia a ativação dos demais recursos
        b_EditarItensDaVenda.setEnabled(true);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
        b_Cancelar.setEnabled(false);
        b_Ok.setEnabled(false);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(false);   //O BD GERA ID SEQUENCIAL!
        tf_idPacoteTuristico.setEnabled(false);
        tf_cliente.setEnabled(false);
        tf_cartao.setEnabled(false);
        tf_parcelas.setEnabled(false);
        tf_numeroPessoas.setEnabled(false);
        //tf_valorTotal.setEnabled(false);     //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_NENHUM;
    }//GEN-LAST:event_b_CancelarActionPerformed

    /**
     * Ao clicar no botão Ok o modo de manipulação de dados atual é encerrado, confirmando
     * a ação que foi realizada (inserção, modificação ou exclusão) e retornando para o 
     * estado DADOS_NENHUM, reabilitando os botões Inserir, Modificar, Excluir e Atualizar
     * e bloqueando os botões Cancelar e Ok.
     * 
     * Os componentes do painel "Dados do cadastro" ficam novamente bloqueados, para
     * que seja permitido apenas a consulta dos mesmos.
     * @param evt 
     */
    private void b_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_OkActionPerformed
        try {
            switch (modoDeDados){
                case DADOS_INSERIR:
                    int vrTotal = tf_valorTotal.getText().isEmpty()?0:Integer.parseInt(tf_valorTotal.getText());
                    Cliente.getServer().insertVendaDeHospedagem(tf_cliente.getText(), tf_cartao.getText(),
                            Integer.parseInt(tf_parcelas.getText()), Integer.parseInt(tf_numeroPessoas.getText()),
                            vrTotal, Integer.parseInt(tf_idPacoteTuristico.getText()));
                    break;
                case DADOS_MODIFICAR:
                    // TODO criar o comando que modifica os dados na respectiva tabela!
                    break;
                case DADOS_EXCLUIR:
                    // TODO criar o comando que exclui os dados na respectiva tabela!
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Nenhum modo de manipulação de dados está ativo.",
                            "ERRO", JOptionPane.ERROR_MESSAGE);
                    break;
            }
            
            //Bloqueia a ativação de outros modos de manpulação de dados.
            b_Inserir.setEnabled(true);
            b_Modificar.setEnabled(true);
            b_Excluir.setEnabled(true);
            b_Atualizar.setEnabled(true);
            //Bloqueia a ativação dos demais recursos
            b_EditarItensDaVenda.setEnabled(true);
            //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
            b_Cancelar.setEnabled(false);
            b_Ok.setEnabled(false);
            //Libera todos os componentes necessários para o cadastro de um novo item.
            //tf_id.setEnabled(false);   //O BD GERA ID SEQUENCIAL!
            tf_idPacoteTuristico.setEnabled(false);
            tf_cliente.setEnabled(false);
            tf_cartao.setEnabled(false);
            tf_parcelas.setEnabled(false);
            tf_numeroPessoas.setEnabled(false);
            //tf_valorTotal.setEnabled(false);     //CAMPO DE PREENCHIMENTO AUTOMATICO!
            
            //Informa qual o modo de dados que está sendo utilizado neste momento.
            modoDeDados = DADOS_NENHUM;
        } catch (RemoteException ex) {
            Logger.getLogger(IG_Op_VendasHospedagem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_OkActionPerformed

    private void b_EditarItensDaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_EditarItensDaVendaActionPerformed
        if (tf_id.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Nenhuma venda de hospedagem foi selecionada.", 
                        "ERRO", JOptionPane.ERROR_MESSAGE);
        }else{
            IG_Op_Itens_VendasHospedagem ig_Op_Itens_VendasHospedagem = new IG_Op_Itens_VendasHospedagem(
                    Integer.parseInt(tf_id.getText()), tf_cliente.getText()
            );
            ig_Op_Itens_VendasHospedagem.setVisible(true);
        }
        //TODO travar este botão enquanto se edita os itens em venda.
    }//GEN-LAST:event_b_EditarItensDaVendaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_Atualizar;
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_EditarItensDaVenda;
    private javax.swing.JButton b_Excluir;
    private javax.swing.JButton b_Inserir;
    private javax.swing.JButton b_Modificar;
    private javax.swing.JButton b_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable table_elementos;
    private javax.swing.JTable table_itensDosElementos;
    private javax.swing.JTextField tf_cartao;
    private javax.swing.JTextField tf_cliente;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_idPacoteTuristico;
    private javax.swing.JTextField tf_numeroPessoas;
    private javax.swing.JTextField tf_parcelas;
    private javax.swing.JTextField tf_valorTotal;
    // End of variables declaration//GEN-END:variables
}
