/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multicastpeertransacoes;

import DataBase.ControleDB;
import DataBase.FuncoesDB;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe Lopes Zem
 */
public class IG_Login extends javax.swing.JFrame {

    /**
     * Creates new form IG_Login
     */
    public IG_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_idPeer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nomePeer = new javax.swing.JTextField();
        b_iniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Iniciar o programa com qual peer?");

        jLabel2.setText("Informe ou o ID ou o NOME dele.");

        jLabel3.setText("ID: ");

        jLabel4.setText("Nome: ");

        b_iniciar.setText("Iniciar");
        b_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_iniciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idPeer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomePeer)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_idPeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nomePeer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_iniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(256, 201));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iniciarActionPerformed
        try {
            int id = (tf_idPeer.getText().length() > 0) ? Integer.parseInt(tf_idPeer.getText()) : 0;
            String nome = tf_nomePeer.getText();
            String endereco = InetAddress.getLocalHost().getHostAddress();
            
            String sql;
            ResultSet rs;
            ArrayList al;
            
            ControleDB.abrirConexaoDBOficial();
            if (nome.isEmpty()){
                //Pesquisa usando o ID.
                sql = "select p.*, c.quantidade as coins from peer p join carteira c on p.id = c.idpeer where p.id = " + id;
                nome = "peer mistério";
            }else{
                //Pesquisa usando o NOME.
                sql = "select p.*, c.quantidade as coins from peer p join carteira c on p.id = c.idpeer where p.nome = '" + nome + "'";
            }
            rs = ControleDB.consultarDBOficial(sql);
            al = ControleDB.resultSetToArrayList(rs, false);
            
            if (al.size() > 0){
                //Encontrou AO MENOS UM resultado baseado na informação dada pelo usuario.
                this.dispose();
                
                ArrayList<String> peer = (ArrayList) al.get(0);
                
                IG_MAIN igMain = new IG_MAIN(
                        Integer.parseInt(peer.get(0)),
                        (String) peer.get(1),
                        Main.DEFAULT_MULTICAST_ADDRESS,
                        Main.DEFAULT_MULTICAST_PORT,
                        Integer.parseInt(peer.get(3)),
                        Integer.parseInt(peer.get(6))
                );
                igMain.atualizarDadosDoPeer();
                igMain.setVisible(true);
            }else{
                //NENHUM resultado foi encontrado. Então cria um novo peer.
                JOptionPane.showMessageDialog(this,
                        "Não existe um peer cadastrado com o ID e/ou NOME inforado.\n"
                                + "Um novo peer vai ser gerado com as informações dadas.",
                        "Novo Peer sendo criado", JOptionPane.INFORMATION_MESSAGE);
                
                this.dispose();
                
                FuncoesDB.inserirPeer(
                        id,
                        nome,
                        endereco,
                        ""+ Main.DEFAULT_UNICAST_PORT);
                FuncoesDB.iniciaCarteira(id, id, Main.INITIAL_COINS);
                
                FuncoesDB.iniciaCarteiraFake(id, id, Main.INITIAL_COINS);
                
                IG_MAIN igMain = new IG_MAIN(
                        id,
                        nome,
                        Main.DEFAULT_MULTICAST_ADDRESS,
                        Main.DEFAULT_MULTICAST_PORT,
                        Main.DEFAULT_UNICAST_PORT + id,
                        Main.INITIAL_COINS
                );
                igMain.atualizarDadosDoPeer();
                igMain.setVisible(true);
            }
            //ControleDB.fecharConexaoDBOficial();  //Removido, pois a concorrêcia de threads durante a inicialização 
                                                    //é afetada com o banco sendo aberto e fechado constantmente.
        } catch (UnknownHostException ex) {
            Logger.getLogger(IG_Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_b_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IG_Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_idPeer;
    private javax.swing.JTextField tf_nomePeer;
    // End of variables declaration//GEN-END:variables
}
