/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceGrafica.Cadastros;

import Database.Operations.DatabaseOperations;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Database.Operations.DbUtils;
/**
 *
 * @author Felipe Lopes Zem
 */
public class IG_Cad_Hoteis extends javax.swing.JFrame {
    private static final byte 
            DADOS_NENHUM = 0, 
            DADOS_INSERIR = 1, 
            DADOS_MODIFICAR = 2,
            DADOS_EXCLUIR = 3;
    
    /**
     * Use esta variável para identificar qual o modo de manipulação de dados está 
     * sendo utilizado no presente momento por este componente da Interface Gráfica.
     * 
     * As constantes aceitas são: DADOS_NENHUM (nenhum, apenas consulta), DADOS_INSERIR, 
     * DADOS_MODIFICAR, DADOS_EXCLUIR.
     */
    private byte modoDeDados = 0;
    
    /**
     * Creates new form IG_CadastroSimples_teste
     */
    public IG_Cad_Hoteis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        DISTRIBUIDOSRMIPUEntityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("DISTRIBUIDOSRMIPU").createEntityManager();
        hoteisQuery = java.beans.Beans.isDesignTime() ? null : DISTRIBUIDOSRMIPUEntityManager0.createQuery("SELECT h FROM Hoteis h");
        hoteisList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : hoteisQuery.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_elementos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_idLocal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_nomeLocal = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        b_Inserir = new javax.swing.JButton();
        b_Modificar = new javax.swing.JButton();
        b_Excluir = new javax.swing.JButton();
        b_Atualizar = new javax.swing.JButton();
        b_Cancelar = new javax.swing.JButton();
        b_Ok = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Todos os hoteis"));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, hoteisList, table_elementos);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${id}"));
        columnBinding.setColumnName("Id");
        columnBinding.setColumnClass(Integer.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${idLocal}"));
        columnBinding.setColumnName("Id Local");
        columnBinding.setColumnClass(Integer.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(table_elementos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do cadastro"));

        jLabel1.setText("ID");

        tf_id.setEnabled(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, table_elementos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.id}"), tf_id, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel2.setText("Nome");

        tf_nome.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, table_elementos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), tf_nome, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel3.setText("ID do Local");

        tf_idLocal.setEnabled(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, table_elementos, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.idLocal}"), tf_idLocal, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jLabel4.setText("Nome do Local");

        tf_nomeLocal.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nomeLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_idLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_nomeLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 212, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        b_Inserir.setText("Inserir");
        b_Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_InserirActionPerformed(evt);
            }
        });

        b_Modificar.setText("Modificar");
        b_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ModificarActionPerformed(evt);
            }
        });

        b_Excluir.setText("Excluir");
        b_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ExcluirActionPerformed(evt);
            }
        });

        b_Atualizar.setText("Atualizar");
        b_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_AtualizarActionPerformed(evt);
            }
        });

        b_Cancelar.setText("Cancelar");
        b_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_CancelarActionPerformed(evt);
            }
        });

        b_Ok.setText("Ok");
        b_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(b_Inserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Modificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(b_Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_Ok))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {b_Atualizar, b_Cancelar, b_Excluir, b_Inserir, b_Modificar, b_Ok});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(b_Inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(b_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(b_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(b_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(b_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b_Atualizar, b_Cancelar, b_Excluir, b_Inserir, b_Modificar, b_Ok});

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ESTE MÉTODO SÓ DEVE SER UTILIZADO PARA TESTAR INDIVIDUALMENTE ESTE MÓDULO!
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new IG_Cad_Hoteis().setVisible(true);
        });
    }
    
    /**
     * Ao clicar no botão Inserir é ativado o modo de Inserção de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que um
     * novo item seja cadastrado.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a inclusão. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_InserirActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(false);
        b_Modificar.setEnabled(false);
        b_Excluir.setEnabled(false);
        b_Atualizar.setEnabled(false);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da inclusão.
        b_Cancelar.setEnabled(true);
        b_Ok.setEnabled(true);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(true);   //O BD GERA ID SEQUENCIAL!
        tf_nome.setEnabled(true);
        tf_idLocal.setEnabled(true);
        //tf_nomeLocal.setEnabled(true);    //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Limpa os campos de edição dos componentes, para que novos valores sejam informados.
        tf_id.setText("");
        tf_nome.setText("");
        tf_idLocal.setText("");
        tf_nomeLocal.setText("");
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_INSERIR;
    }//GEN-LAST:event_b_InserirActionPerformed

    /**
     * Ao clicar no botão Modificar é ativado o modo de Modificação de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que o
     * ítem que estiver selecionado no painel "Todos os itens" possa ser modificado.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a modificação. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ModificarActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(false);
        b_Modificar.setEnabled(false);
        b_Excluir.setEnabled(false);
        b_Atualizar.setEnabled(false);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
        b_Cancelar.setEnabled(true);
        b_Ok.setEnabled(true);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(true);   //O BD GERA ID SEQUENCIAL!
        tf_nome.setEnabled(true);
        tf_idLocal.setEnabled(true);
        //tf_nomeLocal.setEnabled(true);    //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_MODIFICAR;
    }//GEN-LAST:event_b_ModificarActionPerformed

    /**
     * Ao clicar no botão Excluir é ativado o modo de Exclusão de dados. A interface
     * gráfica libera os componentes do painel "Dados do cadastro", para que o
     * ítem que estiver selecionado no painel "Todos os itens" possa ser excluído.
     * 
     * Os botões Cancelar e Ok também são liberados para que seja possível sair
     * deste modo, cancelando ou confirmando a exclusão. Os demais botões são bloqueados
     * enquanto isto.
     * @param evt 
     */
    private void b_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ExcluirActionPerformed
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_EXCLUIR;
        //TODO usar JOPtionPane para confirmar a exclusão
    }//GEN-LAST:event_b_ExcluirActionPerformed

    /**
     * Ao clicar no botão Atualizar todos os dados de itens já cadastrados no painel
     * "Todos os itens" são atualizados.
     * @param evt 
     */
    private void b_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_AtualizarActionPerformed
        ResultSet rs = DatabaseOperations.consultarDB("select * from hoteis");
        table_elementos.setModel(DbUtils.resultSetToTableModel(rs));
        DatabaseOperations.fecharConexãoDB();
    }//GEN-LAST:event_b_AtualizarActionPerformed

    /**
     * Ao clicar no botão Cancelar o modo de manipulação de dados atual é abortado,
     * retornando para o estado DADOS_NENHUM, reabilitando os botões Inserir, Modificar,
     * Excluir e Atualizar e bloqueando os botões Cancelar e Ok.
     * 
     * Os componentes do painel "Dados do cadastro" ficam novamente bloqueados, para
     * que seja permitido apenas a consulta dos mesmos.
     * @param evt 
     */
    private void b_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_CancelarActionPerformed
        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(true);
        b_Modificar.setEnabled(true);
        b_Excluir.setEnabled(true);
        b_Atualizar.setEnabled(true);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
        b_Cancelar.setEnabled(false);
        b_Ok.setEnabled(false);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(false);   //O BD GERA ID SEQUENCIAL!
        tf_nome.setEnabled(false);
        tf_idLocal.setEnabled(false);
        //tf_nomeLocal.setEnabled(false);    //CAMPO DE PREENCHIMENTO AUTOMATICO!
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_NENHUM;
    }//GEN-LAST:event_b_CancelarActionPerformed

    /**
     * Ao clicar no botão Ok o modo de manipulação de dados atual é encerrado, confirmando
     * a ação que foi realizada (inserção, modificação ou exclusão) e retornando para o 
     * estado DADOS_NENHUM, reabilitando os botões Inserir, Modificar, Excluir e Atualizar
     * e bloqueando os botões Cancelar e Ok.
     * 
     * Os componentes do painel "Dados do cadastro" ficam novamente bloqueados, para
     * que seja permitido apenas a consulta dos mesmos.
     * @param evt 
     */
    private void b_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_OkActionPerformed
        switch (modoDeDados){
            case DADOS_INSERIR:
                DatabaseOperations.insertHotel(tf_nome.getText(), Integer.parseInt(tf_idLocal.getText()));
                break;
            case DADOS_MODIFICAR:
                // TODO criar o comando que modifica os dados na respectiva tabela!
                break;
            case DADOS_EXCLUIR:
                // TODO criar o comando que exclui os dados na respectiva tabela!
                break;
            default:
                JOptionPane.showMessageDialog(this, "Nenhum modo de manipulação de dados está ativo.", 
                        "ERRO", JOptionPane.ERROR_MESSAGE);
                break;
        }

        //Bloqueia a ativação de outros modos de manpulação de dados.
        b_Inserir.setEnabled(true);
        b_Modificar.setEnabled(true);
        b_Excluir.setEnabled(true);
        b_Atualizar.setEnabled(true);
        //Libera a saída deste modo, permitindo o cancelamento ou a confirmação da modificação.
        b_Cancelar.setEnabled(false);
        b_Ok.setEnabled(false);
        //Libera todos os componentes necessários para o cadastro de um novo item.
        //tf_id.setEnabled(false);   //O BD GERA ID SEQUENCIAL!
        tf_nome.setEnabled(false);
        tf_idLocal.setEnabled(false);
        tf_nomeLocal.setEnabled(false);
        
        //Informa qual o modo de dados que está sendo utilizado neste momento.
        modoDeDados = DADOS_NENHUM;
    }//GEN-LAST:event_b_OkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager DISTRIBUIDOSRMIPUEntityManager0;
    private javax.swing.JButton b_Atualizar;
    private javax.swing.JButton b_Cancelar;
    private javax.swing.JButton b_Excluir;
    private javax.swing.JButton b_Inserir;
    private javax.swing.JButton b_Modificar;
    private javax.swing.JButton b_Ok;
    private java.util.List<Database.Hoteis> hoteisList;
    private javax.persistence.Query hoteisQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_elementos;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_idLocal;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_nomeLocal;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
